export interface JV_Consumido_Indicadores{
    fecha_cargue: string;
    ganancias: number;
    saldos: number;
    recargas: number;
}

export interface JV_Consumido_Ganancias {
    cod_consumido_ganancias?: number;
    fecha_cargue: string;
    nombre: string ;
    codigo_cliente: string ;
    cc: string ;
    perfil: string ;
    davivienda_pago_tarjeta_de_credito: number ;
    davivienda_pago_de_credito: number ;
    davivienda_deposito_davivienda: number ;
    davivienda_retiro_davivienda: number ;
    aval_tarjeta_de_credito_ban_bogota: number ;
    aval_cred_rotativo_crediservices_dinero_extra_ban_bogota: number ;
    aval_credito_hipotecario_ban_bogota: number ;
    aval_otros_creditos_ban_bogota: number ;
    aval_credito_motos_vehiculos_ban_bogota: number ;
    xbox_plata: number ;
    imvu: number ;
    keo: number ;
    sisteCredito: number ;
    claro: number ;
    paquetes_claro: number ;
    sura: number ;
    movistar: number ;
    paquetes_movistar: number ;
    tigo: number ;
    paquetes_tigo: number ;
    avantel: number ;
    paquetes_avantel: number ;
    virgin: number ;
    paquetes_virgin: number ;
    etb: number ;
    paquete_etb: number ;
    exito: number ;
    paquetes_exito: number ;
    paquetes_conectame: number ;
    flashMobile: number ;
    direcTv: number ;
    wom: number ;
    paquetes_wom: number ;
    kalley_mobile: number ;
    paquetes_kalley_mobile: number ;
    wings_mobile: number ;
    paquetes_wings_mobile: number ;
    unicorn: number ;
    wplay: number ;
    mega_apuesta: number ;
    ya_juego: number ;
    aqui_juego: number ;
    rushBet: number ;
    rivalo: number ;
    miJugada: number ;
    facturas_otros: number ;
    facturas_de_gas_energia: number ;
    sms: number ;
    baloto: number ;
    baloto_pago_de_premios: number ;
    certificado_de_tradicion: number ;
    runt: number ;
    energia_prepago_essa: number ;
    energia_Prepago_epm: number ;
    soat_moto_estado: number ;
    soat_carro_estado: number ;
    soat_bus_estado: number ;
    axa_soat_moto: number ;
    axa_soat_carro: number ;
    axa_soat_publico: number ;
    movii_recargas: number ;
    movii_retiros: number ;
    daviplata_recargas: number ;
    daviplata_retiros: number ;
    taxia_recargas: number ;
    tpaga_retiros: number ;
    razer_gold: number ;
    netflix: number ;
    spotify: number ;
    payValida: number ;
    freeFire: number ;
    noggin: number ;
    crunchyroll: number ;
    office: number ;
    win_sport: number ;
    dataCredito: number ;
    paramount: number ;
    xbox_suscripciones: number ;
    play_station: number ;
    play_station_suscripciones: number ;
    minecraft: number ;
    rixty: number ;
    payCash: number ;
    total: number
}

export interface JV_Consumido_Saldo {
    cod_consumido_saldo?: number;
    fecha_cargue: string;
    nombre: string ;
    codigo_cliente: string ;
    cc: string ;
    perfil: string ;
    davivienda_pago_tarjeta_de_credito: number ;
    davivienda_pago_de_credito: number ;
    davivienda_deposito_davivienda: number ;
    davivienda_retiro_davivienda: number ;
    aval_tarjeta_de_credito_ban_bogota: number ;
    aval_cred_rotativo_crediservices_dinero_extra_ban_bogota: number ;
    aval_credito_hipotecario_ban_bogota: number ;
    aval_otros_creditos_ban_bogota: number ;
    aval_credito_motos_vehiculos_ban_bogota: number ;
    xbox_plata: number ;
    imvu: number ;
    keo: number ;
    sisteCredito: number ;
    claro: number ;
    paquetes_claro: number ;
    sura: number ;
    movistar: number ;
    paquetes_movistar: number ;
    tigo: number ;
    paquetes_tigo: number ;
    avantel: number ;
    paquetes_avantel: number ;
    virgin: number ;
    paquetes_virgin: number ;
    etb: number ;
    paquete_etb: number ;
    exito: number ;
    paquetes_exito: number ;
    paquetes_conectame: number ;
    flashMobile: number ;
    direcTv: number ;
    wom: number ;
    paquetes_wom: number ;
    kalley_mobile: number ;
    paquetes_kalley_mobile: number ;
    wings_mobile: number ;
    paquetes_wings_mobile: number ;
    unicorn: number ;
    wplay: number ;
    mega_apuesta: number ;
    ya_juego: number ;
    aqui_juego: number ;
    rushBet: number ;
    rivalo: number ;
    miJugada: number ;
    facturas_otros: number ;
    facturas_de_gas_energia: number ;
    sms: number ;
    baloto: number ;
    baloto_pago_de_premios: number ;
    certificado_de_tradicion: number ;
    runt: number ;
    energia_prepago_essa: number ;
    energia_Prepago_epm: number ;
    soat_moto_estado: number ;
    soat_carro_estado: number ;
    soat_bus_estado: number ;
    axa_soat_moto: number ;
    axa_soat_carro: number ;
    axa_soat_publico: number ;
    movii_recargas: number ;
    movii_retiros: number ;
    daviplata_recargas: number ;
    daviplata_retiros: number ;
    taxia_recargas: number ;
    tpaga_retiros: number ;
    razer_gold: number ;
    netflix: number ;
    spotify: number ;
    payValida: number ;
    freeFire: number ;
    noggin: number ;
    crunchyroll: number ;
    office: number ;
    win_sport: number ;
    dataCredito: number ;
    paramount: number ;
    xbox_suscripciones: number ;
    play_station: number ;
    play_station_suscripciones: number ;
    minecraft: number ;
    rixty: number ;
    payCash: number ;
    total: number
}

export interface JV_Consumido_Recargas {
    cod_consumido_recargas?: number;
    fecha_cargue: string;
    nombre: string;
    codigo_cliente: string;
    cc: string;
    perfil: string;
    comision: string;
    ayudas_a_familias: number;
    claro: number;
    paquetes_claro: number;
    paquetes_movistar: number;
    movistar: number;
    paquetes_tigo: number;
    tigo: number;
    avantel: number;
    paquetes_avantel: number;
    virgin: number;
    paquetes_virgin: number;
    paquete_etb: number;
    etb: number;
    exito: number;
    paquetes_exito: number;
    paquetes_conectame: number;
    conectame: number;
    sipmobile: number;
    flashmobile: number;
    directv: number;
    iyo_movil: number;
    comunicamos: number;
    wom: number;
    paquetes_wom: number;
    kalley_mobile: number;
    paquetes_kalley: number;
    total: number;
}
